[build-system]
requires = [
    "setuptools >= 42",
    "wheel",
    "pybind11 ~= 2.12",
    "Amulet-pybind11-extensions @ git+https://github.com/Amulet-Team/Amulet-pybind11-extensions.git@6d272873c277f1aeda94740d1897ee3464803bce",
    "versioneer"
]
build-backend = "setuptools.build_meta"
